# Generated by Django 5.1.1 on 2024-10-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics"
            ),
        ),
    ]
