# Generated by Django 5.1.1 on 2024-10-07 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_blogpost_post_userprofile_delete_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
    ]
